### ISSUE TITLE
PHP preloading

### ISSUE THREAD

**Issue by Nyholm** [brefphp/symfony-bridge#13]
If I create a preloading script, then some classes in the cache directory will be preloaded, right?

If we move those classes, they will not be preloaded. 
If we symlink them, then we have to do a filsystem lookup, and then we find a preloaded class. 

The filesystem lookup will be cached with the [default PHP.ini](https://github.com/brefphp/bref/blob/master/runtime/layers/fpm/php.ini#L18). 

But does this mean we should symlink as much as possible?

**Comment by Nemo64** [comment]
The preload file normally does not include cache files, just service classes and the _generated_ container, which must be symlinked because it contains require statements.

**Comment by Nemo64** [comment]
Besides, do you use that feature? I tried it once with bref and [it wasn't so great](https://github.com/symfony/symfony/issues/35759) and consistently decreased performance for small requests.

**Comment by Nyholm** [comment]
Yes, I've tried. You just have to be smart about it. https://developer.happyr.com/php-74-preload

Symfony 5.1 is bringing some really cool improvements here. 

> The preload file normally does not include cache files

I opened this issue to make sure we dont shoot ourselves in the foot. =)

**Comment by Nyholm** [comment]
Preloading works before the first request comes in. So the bridge will never stop the preloading script from working. 

It could potentially damage something, bu tas @Nemo64 says, the preloader script does not preload things in the cache directory. 

Also see #18
