### ISSUE TITLE
`BrefKernel` should make sure `/tmp/log` dir exists

### ISSUE THREAD

**Issue by vhenzl** [brefphp/symfony-bridge#42]
Symfony `about` console command displays info about log directory. If executed in Lambda with pre-warmed cache, it fails with `Error thrown while running command "about". Message: "RecursiveDirectoryIterator::__construct(/tmp/log): failed to open dir: No such file or directory"` error.

The relevant parts in the command are https://github.com/symfony/symfony/blob/db321016cc/src/Symfony/Bundle/FrameworkBundle/Command/AboutCommand.php#L87 and https://github.com/symfony/symfony/blob/db321016cc/src/Symfony/Bundle/FrameworkBundle/Command/AboutCommand.php#L115-L120

The code assumes that the log dir always exist, which is true for a standard Symfony application – `Kernel::buildContainer()` creates the dir if needed: https://github.com/symfony/symfony/blob/db321016cc693d7155042918c667fdaa2d5f72bc/src/Symfony/Component/HttpKernel/Kernel.php#L634-L642

However, if the app is pre-warmed before deploying to AWS, `Kernel::buildContainer()` doesn't get called in Lambda, `/tmp/log` isn't created and `about` command fails.

There are probably more ways how to make sure the log dir exists, but I feel like it's something `BrefKernel` should take care of.

**Comment by mnapoli** [comment]
Thank you for all these details, that sounds very reasonable indeed! If anyone is up for a PR that would be awesome.

I'm not sure if checking + creating the directory [here](https://github.com/brefphp/symfony-bridge/blob/6156395329df3bb34a9a17c5e440ca8ab76c173f/src/BrefKernel.php#L33-L34) would make sense, as that could run quite often? (I'm not sure)

Maybe in [boot()](https://github.com/brefphp/symfony-bridge/blob/6156395329df3bb34a9a17c5e440ca8ab76c173f/src/BrefKernel.php#L62-L67)?

**Comment by vhenzl** [comment]
I went with `boot()`, it seems to be the right place.
