### ISSUE TITLE
ErrorException: Warning: touch(): Unable to create file /var/task/var/cache/dev/ContainerNh8GyCz.legacy because Read-only file system

### ISSUE THREAD

**Issue by trq** [brefphp/symfony-bridge#60]
```
ErrorException:
Warning: touch(): Unable to create file /var/task/var/cache/dev/ContainerNh8GyCz.legacy because Read-only file system

  at /var/task/vendor/symfony/http-kernel/Kernel.php:571
  at Symfony\Component\HttpKernel\Kernel->initializeContainer()
     (/var/task/vendor/symfony/http-kernel/Kernel.php:767)
  at Symfony\Component\HttpKernel\Kernel->preBoot()
     (/var/task/vendor/symfony/http-kernel/Kernel.php:190)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (/var/task/vendor/bref/symfony-bridge/src/BrefKernel.php:48)
  at Bref\SymfonyBridge\BrefKernel->handle()
     (/var/task/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php:35)
  at Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
     (/var/task/vendor/autoload_runtime.php:29)
  at require_once('/var/task/vendor/autoload_runtime.php')
     (/var/task/public/index.php:5)
```

symfony 6.1.1
bref 1.7.0
bref/symfony-bridge 0.2.0
serverless 3.20.0

I have been able to reproduce this quite easily and have a repo available here https://github.com/trq/bref-bug

The steps to reproduce are essentially listed within the commit of this repo: https://github.com/trq/bref-bug/commits/main

Once completed, all I did was:

```
php bin/console cache:warm --env=dev
yarn run deploy
```

Resulting in:

<img width="1084" alt="Screen Shot 2022-07-13 at 11 25 55 am" src="https://user-images.githubusercontent.com/32683/178628616-8f0a15c4-35a7-49a6-a9d0-fa38192a8890.png">

**Comment by trq** [comment]
Sorry, I didn't mean to just dump this in here and expect to get help fixing it, but am wondering if I have just missed something obvious as I don't think I've done anything but follow the typical install really.

Happy to help track down the problem if it indeed isn't something I've missed.

**Comment by mnapoli** [comment]
Could it be that the application run in "prod" environment in Lambda, and you generated the cache for the "dev" environment?

> I don't think I've done anything but follow the typical install really.

Have you followed what's documented in the Bref docs? Just trying to make sure if there's something wrong with the default path we document.

**Comment by trq** [comment]
> Could it be that the application run in "prod" environment in Lambda, and you generated the cache for the "dev" environment?

No, I haven't yet ever deployed or ran the app in prod. Double checked multiple times including just now when I've seen your message.

> Have you followed what's documented in the Bref docs?

Definitely. Pretty much word for word. The example repo https://github.com/trq/bref-bug reproduces this issue.

**Comment by trq** [comment]
Actually, something else about this comment:

> Could it be that the application run in "prod" environment in Lambda, and you generated the cache for the "dev" environment?

If I don't pre generate the cache this issue doesn't happen. So if I'd generated  dev but ran prod the issue wouldn't happen. It only happens when the cache is pre generated.

**Comment by mnapoli** [comment]
Sorry for the delay. As Thibaut mentioned in Slack, I'm not sure either it makes sense to run in "dev" in Lambda, the bridge is optimized for "prod".

Any reason you don't want to run in prod mode?

**Comment by trq** [comment]
Yeah, sorry, that makes perfect sense actually. Really, I was just testing a deployment and didn't want to risk hitting my staging or prod dbs, but it definitely makes sense that _dev_ is the cause of this issue.
