### ISSUE TITLE
Add a warning if the container is rebuild in production

### ISSUE THREAD

**Issue by Nemo64** [brefphp/symfony-bridge#7]
The Kernel should write a warning if the Kernel is build within the lambda environment.

This is probably easy by overwriting the `dumpContainer()` method.
If that is called while `isLambda()` is true, then this is not desirable.

**Comment by mnapoli** [comment]
I'm not sure we should log a warning on every cold start for this. If users prefer not dealing with building the cache before deploying, that's fine as well.

**Comment by Nemo64** [comment]
They can just ignore it but if you are looking at the log, you'll know that there is basically free potential for optimization.
And for those who do want to optimize, it is important information that something is going wrong.

**Comment by Nemo64** [comment]
i accidentally referenced the wrong issue. #10 should be closed.

**Comment by Nyholm** [comment]
Hm. 

Sure it makes sense to warn.. but at the same time, I dont think any user would look in the logs and read the warning to figure out they have slow response time. They are much more likely to see the slow response time (either in browser or in logs). The Bref documentation should warn/promote prewarmed cache. 

I suggest closing this.
