### ISSUE TITLE
Custom error handling during boot

### ISSUE THREAD

**Issue by Nemo64** [brefphp/symfony-bridge#9]
There is absolutely no error handling during kernel boot. The `initializeContainer` method even silences warnings (see [Kernel.php](https://github.com/symfony/http-kernel/blob/v5.0.7/Kernel.php#L432)).

If there is a problem (eg. because of write errors), then you'll just get a white page with nothing logged.

**Comment by Nyholm** [comment]
How can we fix this?

**Comment by Nemo64** [comment]
I might just have found a way to reduce the complexity of this library tremendously. see: https://github.com/brefphp/symfony-bridge/issues/6#issuecomment-612461206

So it might not be necessary to add special logging for write errors because they they shouldn't exist.

**Comment by Nemo64** [comment]
I think this isn't needed anymore.
The problem I was talking about only occurs if the container has problems dumping.
This should not happen since the root of the cache dir is always writable (unless overwriting of the cache dir fails for some reason).

Every other cache write happens when normal logging is working.

Sidenote: System cache write errors will trigger warnings which are not logged in production by default.
